version: '3'
services: 
  api4yoloyr:
    image: thanatoszeroth/api4yoloyr:2022.09
    container_name: api4yoloyr
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
      - ServiceDomainName=0.0.0.0
      - ServiceDomainPort=19191
      - yolor_device=0
      - yolor_conf_thres=0.3
      - yolor_iou_thres=0.3
      - yolor_weights=/yolor_models/yolor_p6.pt
      - yolor_cfg=/yolor_models/yolor_p6.cfg
      - yolor_names=/yolor_models/coco.names
    volumes:
      - $PWD/yolor_models:/yolor_models
    ports:
      - 19191:19191
    command:
      - docker-entrypoint.sh




